steps:
    - name: 'gcr.io/cloud-builders/docker'
      id: 'pull-cache'
      entrypoint: 'bash'
      args:
          - '-c'
          - 'docker pull southamerica-east1-docker.pkg.dev/valorizeaitcc/valorize-repo/valorizeai:latest || exit 0'

    # Standard AMD64 build for Cloud Run
    - name: 'gcr.io/cloud-builders/docker'
      id: 'build-image'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              docker build \
                -f docker/laravel/Dockerfile \
                --cache-from southamerica-east1-docker.pkg.dev/valorizeaitcc/valorize-repo/valorizeai:latest \
                -t southamerica-east1-docker.pkg.dev/valorizeaitcc/valorize-repo/valorizeai:latest \
                .
      waitFor: ['pull-cache']
      env:
          - 'DOCKER_BUILDKIT=1'

    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'push'
          - 'southamerica-east1-docker.pkg.dev/valorizeaitcc/valorize-repo/valorizeai:latest'
      id: 'push-latest-image'
      waitFor: ['build-image']

# options:
#     machineType: 'E2_HIGHCPU_8'
#     logging: CLOUD_LOGGING_ONLY
#     env:
#         - 'DOCKER_BUILDKIT=1'

images:
    - 'southamerica-east1-docker.pkg.dev/valorizeaitcc/valorize-repo/valorizeai:latest'

timeout: '1200s'
