version: '3.8'

services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:17.2}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - '${DB_PUBLISHED_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - source: postgres_password
        target: postgres_password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first

volumes:
  postgres_data:
    external: true
    name: ${DB_DATA_VOLUME:-postgres_data}

secrets:
  postgres_password:
    external: true
    name: ${POSTGRES_PASSWORD_SECRET_NAME:-postgres_password}
