{
 "title": "Logs & Traces",
 "tags": [ "observability" ],
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "traceid", "label": "Trace ID" },
   {
    "name": "service_name",
    "label": "Name",
    "query": {
     "query": "label_values(target_info{service_namespace=~\"$service_namespace\", deployment_environment_name=~\"$deployment_environment_name\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs (filtered by traceid)",
   "type": "logs",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"valorizeai\"} | traceid =~ `$traceid`"
    }
   ]
  },
  {
   "title": "Trace View (by ID)",
   "type": "traces",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "query": "$traceid" }
   ]
  },
  {
   "title": "Recent Traces (by Service)",
   "type": "traces",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "query": "{service.name=*}" }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "type": "table",
   "description": "Traces containing a span emitted by the service",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 52 },
   "targets": [
    {
     "filters": [
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      },
      {
       "id": "6997e808",
       "operator": "=",
       "scope": "resource",
       "tag": "deployment.environment.name",
       "value": [ "$deployment_environment_name" ],
       "valueType": "string"
      },
      {
       "id": "e9f0e855",
       "operator": "=",
       "scope": "resource",
       "tag": "service.namespace",
       "value": [ "$service_namespace" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$service_name\"} | select(status)",
     "tableType": "spans"
    }
   ]
  }
 ]
}