<?php

declare(strict_types=1);

namespace App\Enums;

enum Currency: string
{
    case BRL = 'BRL'; // Brazilian real
    case USD = 'USD'; // United States dollar
    case EUR = 'EUR';
    // case AED = 'AED'; // United Arab Emirates dirham
    // case AFN = 'AFN'; // Afghan afghani
    // case ALL = 'ALL'; // Albanian lek
    // case AMD = 'AMD'; // Armenian dram
    // case ANG = 'ANG'; // Netherlands Antillean guilder
    // case AOA = 'AOA'; // Angolan kwanza
    // case ARS = 'ARS'; // Argentine peso
    // case AUD = 'AUD'; // Australian dollar
    // case AWG = 'AWG'; // Aruban florin
    // case AZN = 'AZN'; // Azerbaijani manat
    // case BAM = 'BAM'; // Bosnia and Herzegovina convertible mark
    // case BBD = 'BBD'; // Barbados dollar
    // case BDT = 'BDT'; // Bangladeshi taka
    // case BGN = 'BGN'; // Bulgarian lev
    // case BHD = 'BHD'; // Bahraini dinar
    // case BIF = 'BIF'; // Burundian franc
    // case BMD = 'BMD'; // Bermudian dollar
    // case BND = 'BND'; // Brunei dollar
    // case BOB = 'BOB'; // Boliviano
    // case BOV = 'BOV'; // Bolivian Mvdol (funds code)
    // case BSD = 'BSD'; // Bahamian dollar
    // case BTN = 'BTN'; // Bhutanese ngultrum
    // case BWP = 'BWP'; // Botswana pula
    // case BYN = 'BYN'; // Belarusian ruble
    // case BZD = 'BZD'; // Belize dollar
    // case CAD = 'CAD'; // Canadian dollar
    // case CDF = 'CDF'; // Congolese franc
    // case CHE = 'CHE'; // WIR euro (complementary currency)
    // case CHF = 'CHF'; // Swiss franc
    // case CHW = 'CHW'; // WIR franc (complementary currency)
    // case CLF = 'CLF'; // Unidad de Fomento (funds code)
    // case CLP = 'CLP'; // Chilean peso
    // case CNY = 'CNY'; // Renminbi
    // case COP = 'COP'; // Colombian peso
    // case COU = 'COU'; // Unidad de Valor Real (UVR) (funds code)
    // case CRC = 'CRC'; // Costa Rican colon
    // case CUP = 'CUP'; // Cuban peso
    // case CVE = 'CVE'; // Cape Verdean escudo
    // case CZK = 'CZK'; // Czech koruna
    // case DJF = 'DJF'; // Djiboutian franc
    // case DKK = 'DKK'; // Danish krone
    // case DOP = 'DOP'; // Dominican peso
    // case DZD = 'DZD'; // Algerian dinar
    // case EGP = 'EGP'; // Egyptian pound
    // case ERN = 'ERN'; // Eritrean nakfa
    // case ETB = 'ETB'; // Ethiopian birr
    // case EUR = 'EUR'; // Euro
    // case FJD = 'FJD'; // Fiji dollar
    // case FKP = 'FKP'; // Falkland Islands pound
    // case GBP = 'GBP'; // Pound sterling
    // case GEL = 'GEL'; // Georgian lari
    // case GHS = 'GHS'; // Ghanaian cedi
    // case GIP = 'GIP'; // Gibraltar pound
    // case GMD = 'GMD'; // Gambian dalasi
    // case GNF = 'GNF'; // Guinean franc
    // case GTQ = 'GTQ'; // Guatemalan quetzal
    // case GYD = 'GYD'; // Guyanese dollar
    // case HKD = 'HKD'; // Hong Kong dollar
    // case HNL = 'HNL'; // Honduran lempira
    // case HTG = 'HTG'; // Haitian gourde
    // case HUF = 'HUF'; // Hungarian forint
    // case IDR = 'IDR'; // Indonesian rupiah
    // case ILS = 'ILS'; // Israeli new shekel
    // case INR = 'INR'; // Indian rupee
    // case IQD = 'IQD'; // Iraqi dinar
    // case IRR = 'IRR'; // Iranian rial
    // case ISK = 'ISK'; // Icelandic króna
    // case JMD = 'JMD'; // Jamaican dollar
    // case JOD = 'JOD'; // Jordanian dinar
    // case JPY = 'JPY'; // Japanese yen
    // case KES = 'KES'; // Kenyan shilling
    // case KGS = 'KGS'; // Kyrgyzstani som
    // case KHR = 'KHR'; // Cambodian riel
    // case KMF = 'KMF'; // Comoro franc
    // case KPW = 'KPW'; // North Korean won
    // case KRW = 'KRW'; // South Korean won
    // case KWD = 'KWD'; // Kuwaiti dinar
    // case KYD = 'KYD'; // Cayman Islands dollar
    // case KZT = 'KZT'; // Kazakhstani tenge
    // case LAK = 'LAK'; // Lao kip
    // case LBP = 'LBP'; // Lebanese pound
    // case LKR = 'LKR'; // Sri Lankan rupee
    // case LRD = 'LRD'; // Liberian dollar
    // case LSL = 'LSL'; // Lesotho loti
    // case LYD = 'LYD'; // Libyan dinar
    // case MAD = 'MAD'; // Moroccan dirham
    // case MDL = 'MDL'; // Moldovan leu
    // case MGA = 'MGA'; // Malagasy ariary
    // case MKD = 'MKD'; // Macedonian denar
    // case MMK = 'MMK'; // Myanmar kyat
    // case MNT = 'MNT'; // Mongolian tögrög
    // case MOP = 'MOP'; // Macanese pataca
    // case MRU = 'MRU'; // Mauritanian ouguiya
    // case MUR = 'MUR'; // Mauritian rupee
    // case MVR = 'MVR'; // Maldivian rufiyaa
    // case MWK = 'MWK'; // Malawian kwacha
    // case MXN = 'MXN'; // Mexican peso
    // case MXV = 'MXV'; // Mexican Unidad de Inversion (UDI) (funds code)
    // case MYR = 'MYR'; // Malaysian ringgit
    // case MZN = 'MZN'; // Mozambican metical
    // case NAD = 'NAD'; // Namibian dollar
    // case NGN = 'NGN'; // Nigerian naira
    // case NIO = 'NIO'; // Nicaraguan córdoba
    // case NOK = 'NOK'; // Norwegian krone
    // case NPR = 'NPR'; // Nepalese rupee
    // case NZD = 'NZD'; // New Zealand dollar
    // case OMR = 'OMR'; // Omani rial
    // case PAB = 'PAB'; // Panamanian balboa
    // case PEN = 'PEN'; // Peruvian sol
    // case PGK = 'PGK'; // Papua New Guinean kina
    // case PHP = 'PHP'; // Philippine peso
    // case PKR = 'PKR'; // Pakistani rupee
    // case PLN = 'PLN'; // Polish złoty
    // case PYG = 'PYG'; // Paraguayan guaraní
    // case QAR = 'QAR'; // Qatari riyal
    // case RON = 'RON'; // Romanian leu
    // case RSD = 'RSD'; // Serbian dinar
    // case RUB = 'RUB'; // Russian ruble
    // case RWF = 'RWF'; // Rwandan franc
    // case SAR = 'SAR'; // Saudi riyal
    // case SBD = 'SBD'; // Solomon Islands dollar
    // case SCR = 'SCR'; // Seychelles rupee
    // case SDG = 'SDG'; // Sudanese pound
    // case SEK = 'SEK'; // Swedish krona
    // case SGD = 'SGD'; // Singapore dollar
    // case SHP = 'SHP'; // Saint Helena pound
    // case SLE = 'SLE'; // Sierra Leonean leone
    // case SOS = 'SOS'; // Somalian shilling
    // case SRD = 'SRD'; // Surinamese dollar
    // case SSP = 'SSP'; // South Sudanese pound
    // case STN = 'STN'; // São Tomé and Príncipe dobra
    // case SVC = 'SVC'; // Salvadoran colón
    // case SYP = 'SYP'; // Syrian pound
    // case SZL = 'SZL'; // Swazi lilangeni
    // case THB = 'THB'; // Thai baht
    // case TJS = 'TJS'; // Tajikistani somoni
    // case TMT = 'TMT'; // Turkmenistan manat
    // case TND = 'TND'; // Tunisian dinar
    // case TOP = 'TOP'; // Tongan paʻanga
    // case TRY = 'TRY'; // Turkish lira
    // case TTD = 'TTD'; // Trinidad and Tobago dollar
    // case TWD = 'TWD'; // New Taiwan dollar
    // case TZS = 'TZS'; // Tanzanian shilling
    // case UAH = 'UAH'; // Ukrainian hryvnia
    // case UGX = 'UGX'; // Ugandan shilling
    // case USN = 'USN'; // United States dollar (next day) (funds code)
    // case UYU = 'UYU'; // Uruguayan peso
    // case UYW = 'UYW'; // Unidad previsional
    // case UZS = 'UZS'; // Uzbekistani sum
    // case VED = 'VED'; // Venezuelan digital bolívar
    // case VES = 'VES'; // Venezuelan sovereign bolívar
    // case VND = 'VND'; // Vietnamese đồng
    // case VUV = 'VUV'; // Vanuatu vatu
    // case WST = 'WST'; // Samoan tala
    // case XAF = 'XAF'; // CFA franc BEAC
    // case XAG = 'XAG'; // Silver (one troy ounce)
    // case XAU = 'XAU'; // Gold (one troy ounce)
    // case XBA = 'XBA'; // European Composite Unit (EURCO)
    // case XBB = 'XBB'; // European Monetary Unit (E.M.U.-6)
    // case XBC = 'XBC'; // European Unit of Account 9 (E.U.A.-9)
    // case XBD = 'XBD'; // European Unit of Account 17 (E.U.A.-17)
    // case XCD = 'XCD'; // East Caribbean dollar
    // case XDR = 'XDR'; // Special drawing rights
    // case XOF = 'XOF'; // CFA franc BCEAO
    // case XPD = 'XPD'; // Palladium (one troy ounce)
    // case XPF = 'XPF'; // CFP franc (franc Pacifique)
    // case XPT = 'XPT'; // Platinum (one troy ounce)
    // case XSU = 'XSU'; // SUCRE
    // case XTS = 'XTS'; // Code reserved for testing
    // case XUA = 'XUA'; // ADB Unit of Account
    // case XXX = 'XXX'; // No currency
    // case YER = 'YER'; // Yemeni rial
    // case ZAR = 'ZAR'; // South African rand
    // case ZMW = 'ZMW'; // Zambian kwacha
    // case ZWG = 'ZWG'; // Zimbabwe Gold
}
